version: '3.8'

services:
  postgres:
    image: postgres:13  # Versión de PostgreSQL
    container_name: postgres_db
    environment:
      POSTGRES_USER: itos       # Nombre de usuario de la base de datos
      POSTGRES_PASSWORD: admin123  # Contraseña del usuario
      POSTGRES_DB: metal-api-db    # Nombre de la base de datos
    ports:
      - "5432:5432"  # Mapea el puerto 5432 del contenedor al puerto 5432 del host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos

volumes:
  postgres_data:
