services:
  postgres:
    image: postgres:13  # Versión de PostgreSQL
    container_name: postgres_db
    environment:
      POSTGRES_USER: itos       # Nombre de usuario de la base de datos
      POSTGRES_PASSWORD: 1q2w3e4r  # Contraseña del usuario
      POSTGRES_DB: metal-api-db    # Nombre de la base de datos
    ports:
      - "5432:5432"  # Mapea el puerto 5432 del contenedor al puerto 5432 del host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped    # Persistencia de datos

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
